- name: Mongodb configuration
  hosts: mongodb
  become: yes

  tasks:
  - name: copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb server
    ansible.builtin.dnf:
      name: mongodb-org
      state: present

  - name: allow remote connection
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.0'
      replace: '0.0.0.0'

  - name: mongodb start and enable
    ansible.builtin.service:
      name: mongod
      enabled: yes
      state: started
  - name: restart mongod
    ansible.builtin.service:
      name: mongod
      state: restarted

