# ansible-playbook -i localhost, -e '{"instances:["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]"}' roboshop.yaml
- name: create ec2 instance and route53 records
  hosts: all
  connection: local
  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-0d4fbbcb5f7b89575"
    domain_name: "sanathananelaform.online"
    evn_environment: dev
    action: create
    instances:
    - mongodb
    - catalogue
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ami_id}}"
      name: "{{ item}}-{{evn_environment}}"
      tags:
        Project: roboshop
        Component: "{{ item }}"
        Environment: "{{ item }}- {{evn_environment}}"
      wait: false
    loop: "{{instances}}"
    register: ec2_output
    when: action == "create"

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ec2_output }}"
    when: action == "create"
    #pip3.9 install botocore boto3 we have to install
  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "{{item.item}}-{{evn_environment}}.{{domain_name}}" #mongodb-dev.sanathananelaform.online
      type: A
      value: "{{ item.instances[0].private_ip_address}}"
      ttl: 1
      wait: false
    loop: "{{ec2_output.results}}"
    when: action == "create"

  # create frontend server
  - name: create r53 record
    amazon.aws.route53:
      state: present
      zone: "{{domain_name}}"
      record: "roboshop-{{evn_environment}}.{{domain_name}}" # roboshop-dev.sanathananelaform.online
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address}}"
      wait: true
    loop: "{{ec2_output.results}}"
    when:
    - item.item== "frontend"
    - action == "create"

  - name: delete r53 records
    amazon.aws.route53:
      state: absent
      zone: "{{domain_name}}"
      record: "{{item}}-{{evn_environment}}.{{domain_name}}"
      type: A
      ttl: 1
    loop: "{{instances}}"
    when: action == "destroy"

  - name: delete ec2 instance
    amazon.aws.ec2_instance:
      state: absent
      name: "{{ item }}- {{ evn_environment }}"
    loop: "{{instances}}"
    when: action == "destroy"
